In [3]:
import tensorflow as tf
import numpy as np 

In [12]:
x_train = tf.random.uniform(shape=(6, 4))
y_train = tf.random.uniform(shape=(6, 1), minval=0, maxval=3, dtype=tf.dtypes.int32)
# 6x1, int32 값 0, 1, 2
print(y_train)
x_train_one_hot = tf.one_hot(y_train, depth=3)
y_train_one_hot = tf.reshape(x_train_one_hot, shape=(-1,3))# -1은 알아서 맞추어 주세요
print(y_train_one_hot) 

x_test = tf.random.uniform(shape=(64, 4))
y_test = tf.random.uniform(shape=(64, 1), minval=0, maxval=3, dtype=tf.dtypes.int32)
y_test_one_hot = tf.one_hot(y_test, depth=3)
y_test_one_hot = tf.reshape(y_test_one_hot, shape=(-1,3))

tf.Tensor(
[[0]
 [2]
 [1]
 [0]
 [0]
 [0]], shape=(6, 1), dtype=int32)
tf.Tensor(
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]], shape=(6, 3), dtype=float32)


In [17]:
model = tf.keras.models.Sequential([
    tf.keras.Input(shape=(4,)),
    tf.keras.layers.Dense(units=16, activation='relu'),
    tf.keras.layers.Dense(units=3, activation=None),
    tf.keras.layers.Softmax()
])
model.summary()
yp = model(x_train)
print(yp)


Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 16)                80        
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 51        
_________________________________________________________________
softmax_2 (Softmax)          (None, 3)                 0         
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________
tf.Tensor(
[[0.19875953 0.42880008 0.37244043]
 [0.27811605 0.3873274  0.33455655]
 [0.24021134 0.3861954  0.37359327]
 [0.26133516 0.3618292  0.3768356 ]
 [0.19901004 0.43736938 0.36362064]
 [0.30139744 0.38931313 0.3092894 ]], shape=(6, 3), dtype=float32)


In [22]:
loss_fn = tf.keras.losses.CategoricalCrossentropy(from_logits = False)
optimizer = tf.keras.optimizers.SGD(learning_rate = 0.01)
model.compile(optimizer=optimizer, loss=loss_fn, metric=['accuarcy'])
model.fit(x_train, y_train_one_hot, epochs=100, batch_size=6) 


Train on 6 samples
Epoch 1/100
6/6 [==============================] - 0s 5ms/sample


ValueError: Dimensions must be equal, but are 4 and 3 for 'loss/softmax_loss/softmax_cross_entropy_with_logits' (op: 'SoftmaxCrossEntropyWithLogits') with input shapes: [6,4], [6,3].

In [9]:
model.evaluate(x_train, y_train_one_hot, verbose=2)
model.evaluate(x_test, y_test_one_hot, verbose=2)

RuntimeError: You must compile your model before training/testing. Use `model.compile(optimizer, loss)`.

In [11]:
x_train = tf.random.uniform(shape=(7, 5))
y_train = tf.random.uniform(shape=(7, 1), minval=0, maxval=4, dtype=tf.dtypes.int32)
print(y_train)

#model에 Softmax층 사용.
#label은 one hot으로 변경해서 사용.
#weight의 수? bias의 수? 

x_train_one_hot = tf.one_hot(y_train, depth=4)
y_train_one_hot = tf.reshape(x_train_one_hot, shape=(-1,4))
print(y_train_one_hot) 

x_test = tf.random.uniform(shape=(64, 5))
y_test = tf.random.uniform(shape=(64, 1), minval=0, maxval=4, dtype=tf.dtypes.int32)
y_test_one_hot = tf.one_hot(y_test, depth=4)
y_test_one_hot = tf.reshape(y_test_one_hot, shape=(-1,4))
 

tf.Tensor(
[[0]
 [3]
 [3]
 [3]
 [1]
 [0]
 [1]], shape=(7, 1), dtype=int32)
tf.Tensor(
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]], shape=(7, 4), dtype=float32)


In [33]:
model = tf.keras.models.Sequential([
    tf.keras.Input(shape=(4,)),
    tf.keras.layers.Dense(units=8, activation='relu'),
    tf.keras.layers.Dense(units=4, activation=None),
    tf.keras.layers.Softmax()
])
model.summary()
yp = model(x_train)
print(yp)

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_22 (Dense)             (None, 5)                 25        
_________________________________________________________________
dense_23 (Dense)             (None, 2)                 12        
_________________________________________________________________
softmax_11 (Softmax)         (None, 2)                 0         
Total params: 37
Trainable params: 37
Non-trainable params: 0
_________________________________________________________________
tf.Tensor(
[[0.5512384  0.44876167]
 [0.6241044  0.37589565]
 [0.42894512 0.5710549 ]
 [0.5983949  0.40160516]
 [0.5080051  0.49199495]
 [0.48501414 0.5149858 ]], shape=(6, 2), dtype=float32)


In [16]:
loss_fn = tf.keras.losses.CategoricalCrossentropy(from_logits = False)
optimizer = tf.keras.optimizers.SGD(learning_rate = 0.01)
model.compile(optimizer=optimizer, loss = loss_fn, metric=['accuarcy'])
model.fit(x_train, y_train_one_hot, epochs=100, batch_size=6) 

Train on 6 samples
Epoch 1/100
6/6 [==============================] - 0s 5ms/sample


ValueError: Dimensions must be equal, but are 4 and 3 for 'loss/softmax_loss/softmax_cross_entropy_with_logits' (op: 'SoftmaxCrossEntropyWithLogits') with input shapes: [6,4], [6,3].